# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Amazon-SimpleDB
version:      0.03
version_from: lib/Amazon/SimpleDB.pm
installdirs:  site
requires:
    Digest::HMAC_SHA1:             0
    LWP::UserAgent:                0
    Test::More:                    0.01
    URI:                           0
    XML::Simple:                   1.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
